### ISSUE TITLE
The problem with "Mark as front element" in netedit when you want to use it for two edges

### ISSUE THREAD

**Issue by MohamadReza-Haghani** [eclipse-sumo/sumo#11197]
Hi,

I created overlapping elements in the 4 directions of an intersection to make exclusive left-turning lanes. I used "Mark as front element" to bring one of the overlapping edges to the front and adjust the connections in netedit. In some situations, the two edges which make a connection are under and I need to bring them to the front to adjust the connection. I used "Mark as front element" for the first edge and it brought it to the front. Then, when I used "Mark as front element" for the second edge, it brought the second edge to the front, but the first edge went under again. I was wondering if there is a way to keep two edges simultaneously in the front.

Thanks!
Reza.

**Comment by m-kro** [comment]
Can you show a screenshot of your intersection? Actually the only case where overlapping edges are OK is when you don't want any interaction between them, e.g. a bridge across another road. You can build exclusive turning lanes just by adding only one connection per lane to the incoming edge.

**Comment by MohamadReza-Haghani** [comment]
Thank you for your response! This is my network. For instance, at intersection 3, I could not bring forward lanes -e8_2_2 and e10_1_2 to remove the connection between them.
[ezyzip.zip](https://github.com/eclipse/sumo/files/9120651/ezyzip.zip)

**Comment by m-kro** [comment]
You can set the connections by supplying your network file and a connections file (see [docs](https://sumo.dlr.de/docs/Networks/PlainXML.html#connection_descriptions)) to [netconvert](https://sumo.dlr.de/docs/netconvert.html). How do you expect the overlapping lanes to work? SUMO offers limited support for [driving in opposite traffic](https://sumo.dlr.de/docs/Networks/PlainXML.html#neighboring_opposite-direction_lanes). Otherwise, you could control the vehicles in the overlapping lanes through TraCI commands.
