### ISSUE TITLE
Redefine relation between charging station and parking

### ISSUE THREAD

**Issue by m-kro** [eclipse-sumo/sumo#13596]
Currently, vehicles can be charged at parking spaces if their stop definition includes both the parking and the charging station (and the position definitions of charging and parking elements overlap enough). This means there is no direct link between a specific parking area and a charging station. Some consequences:

- the number, location and additional properties of available charging points are unknown unless there are vehicles/routes with stop definitions
- the parking has to be tailored to the wanted number of charging points (1 parking space = 1 charging point)
- actual (physical) location of the charging station is unclear, as vehicles on the through lane waiting for a free parking space currently load too

**Comment by namdre** [comment]
I think it has advantages to keep parkingAreas and chargingStations as distinct concepts since they can exist without each other (i.e for inductive charging along a road).

suggestion:
- add a "parkingArea" attribute to the chargingStation 
  - if this attribute is set, the location / dimension of the station could be omitted and copied directly from the parkingArea
- if a chargingStation has a parkingArea, only start to charge if the vehicle is parked there

**Comment by m-kro** [comment]
@behrisch @palvarezlopez For discussion: What about the relation parkingArea -> chargingStation? Should it also be restricted to 1:1 or should a 1:n relation be allowed (with which semantics)?

**Comment by m-kro** [comment]
Postponed until @behrisch returns
