### ISSUE TITLE
Importing_O/D_Matrices：daily_time_lines

### ISSUE THREAD

**Issue by nudtdyk** [eclipse-sumo/sumo#14006]
Hi, I would like to know what is the difference between the following OD matrix cut timelines and what scenarios they apply to：
![image](https://github.com/eclipse-sumo/sumo/assets/120693511/43dcc256-caf2-4e72-9789-cf81976636f4)
As we've seen, some vehicle types don't have a referenced timeline for a given day, so if I want to know how do I need to get it?
Looking forward to your reply！Thanks.

**Comment by nudtdyk** [comment]
Sorry to bother you again, another question I'd like to ask: What can I do to simulate a weekly traffic simulation please?

**Comment by m-kro** [comment]
The cited timelines have been taken from an empiric study which was done in Germany several years ago. Some cases have not been studied because they either are not of interest (less people working on weekends) or because some week days are considered more prone for unsual time lines (e.g. people traveling before/after weekend, holidays starting/ending at that time). 

If you have other sources, you can build your own time line. You can allocate demand for more than 24h with your custom time line (see [docs](https://sumo.dlr.de/docs/Demand/Importing_O/D_Matrices.html#free_range_definitions)).
