### ISSUE TITLE
Identifying all the u-turn movements

### ISSUE THREAD

**Issue by govin08** [eclipse-sumo/sumo#14097]
![image](https://github.com/eclipse-sumo/sumo/assets/65585738/523d03d6-c255-4014-8eed-57a3a9a7e2d2)

The above is my network. blue names correspond to edges and orange names correspond to nodes. The intersection node `n3` has three uturn nodes `u30`, `u31` and `u32`. I want to find the u-turn movement, given an u-turn node. By a movement, I mean an ordered pair of edges. That is, I want to constitute a function `f` that maps a uturn node to the two edges that characterizes the uturn movement (or a set of uturn movements).

In this example, `f` should act like this

`print(f(u30))`
`> (571556452_01, 571556452_02)`

`print(f(u31))`
`> (571500475_02, 571500475_01.26)`

`print(f(u32))`
`> (571540303_02, -571540303_02)`

**My trial** : given `u30`, I could get the set `[571556452_01, 571556450_01]` of all incoming edges and the set `[571556450_02, 571556452_02]` of all outgoing edges. And I can find all the combination of (incoming edge, outgoing edge). But out of these four combination, I couldn't find the way to determine if this combination indicates going straight or uturn.

**Comment by m-kro** [comment]
I assume you use sumolib for this purpose. There you can check the direction attribute of connections `sumolib.net.connection.getDirection()` ([ref](https://sumo.dlr.de/pydoc/sumolib.net.connection.html#Connection)) to identify those connections marked as u-turns. Look for those connections marked with `Connection.LINKDIR_TURN`. Otherwise you could also get the right pair of edges by geometry (comparing their positions and angles).

**Comment by govin08** [comment]
Yeah I use sumolib.

So connections have there information about where to go. Maybe that would be sufficient. Thanks!
