### ISSUE TITLE
Get vehicle travel time

### ISSUE THREAD

**Issue by Danny-wenya** [eclipse-sumo/sumo#14146]
I want to get vehicles' real travel time when it finished it travel throgh the network realtime when the simulation is going on . What API can I use ?  I've thinking about reading the tripinfo log file, but it's inefficiency.

*If possible, upload an example that shows your problem.*

**SUMO-version:**

**operating system:**

**Comment by m-kro** [comment]
This is tricky because vehicles disappear from the simulation once they have completed their route. So you cannot ask for the complete travel time during the simulation. Additionally I recommend not to mess with the file-based output during the simulation as you can't rely on (the latest data may have not been written yet).

The remaining option is to query regularly (every time step if you want the max. time resolution) all vehicles in question whether they are close to finishing their route.  Some hints which [TraCI](https://sumo.dlr.de/docs/TraCI.html) calls may of use in this context:

- `traci.vehicle.getDeparture` [ref](https://sumo.dlr.de/pydoc/traci._vehicle.html#VehicleDomain-getDeparture)
- `traci.vehicle.getRoute` [ref](https://sumo.dlr.de/pydoc/traci._vehicle.html#VehicleDomain-getRoute)
- `traci.vehicle.getLaneID` [ref](https://sumo.dlr.de/pydoc/traci._vehicle.html#VehicleDomain-getLaneID)
- `traci.vehicle.getPosition` [ref](https://sumo.dlr.de/pydoc/traci._vehicle.html#VehicleDomain-getPosition)
- `traci.simulation.getCurrentTime` [ref](https://sumo.dlr.de/pydoc/traci._simulation.html#SimulationDomain-getCurrentTime)
