### ISSUE TITLE
A question on TraCI socket

### ISSUE THREAD

**Issue by thinker310** [eclipse-sumo/sumo#14167]
![image](https://github.com/eclipse-sumo/sumo/assets/62609436/44d3cfba-e9c5-4032-bb06-4ddb8f47c8ce)
Hello, I wonder why is there a lack of  listening (e.g. socket.listen()), after the SUMO port is bound.

**Comment by behrisch** [comment]
The code you highlighted only checks for a free socket, the listening takes place in C++ (because sumo is the server) here: 
https://github.com/eclipse-sumo/sumo/blob/main/src/traci-server/TraCIServer.cpp#L327 respectively here
https://github.com/eclipse-sumo/sumo/blob/main/src/foreign/tcpip/socket.cpp#L314
