### ISSUE TITLE
the SUMO GUI (Graphical User interface)

### ISSUE THREAD

**Issue by wy12184163** [eclipse-sumo/sumo#14184]
"standard", "fast-standard", and "real-world" are some of the simulation modes in the SUMO GUI (Graphical User interface). Can I define a specific simulation model in python instead of having to adjust it manually every time I open the SUMO GUI

**SUMO-version:**1.16

**operating system:**windows

**Comment by m-kro** [comment]
You can't change the visualisation from a script (except for vehicle colours).
Instead of adjusting everything again from the start, [save your visualisation settings](https://sumo.dlr.de/docs/sumo-gui.html#gui-settings_files) and [load ](https://sumo.dlr.de/docs/sumo-gui.html#configuration_files) them (**--gui-settings-file**).
