### ISSUE TITLE
Changing an existing vehicle type with a newly defined vehicle type in simulation.

### ISSUE THREAD

**Issue by transport45678** [eclipse-sumo/sumo#14286]
Hello,
I have a network that consists of four intersections located consecutively. I processed turn-count data using the RouteSampler tool, considering multiple vehicle types (i.e., passenger cars, trucks, buses, etc.). For now, I am able to run the simulation by following the routeSampler documentation instructions. After this point, I would like to change some percentage of passenger cars to automated vehicles to investigate the network-wide impacts. However, I am not sure how to conduct this process. Can you give me a suggestion on how to implement this process in SUMO?
Thank you for your help; regards.

**Comment by m-kro** [comment]
You can choose the routeSampler.py option **--write-flows** (possible values: "number", "probability", "poisson") to get flows instead of single vehicles in the output route file. This would make it easier to edit the vehicle type and the number of vehicles to expect. You can choose as well to subtract the automated vehicles from passenger cars directly in your count data and then repeat the normal routeSample.py process...
