### ISSUE TITLE
10-Fold Network Expansion for Data Augmentation

### ISSUE THREAD

**Issue by govin08** [eclipse-sumo/sumo#14329]
I want to scale up my network by replicating its structure tenfold to augment data, increasing both nodes and edges proportionally.

It's just for an experiment, so the replicated node and edges don't need to be physically distinct : e.g. two junctions can be in the same position if it doesn't make an error. Or it is still alright to locate the replicated network to be disjoint with the original network.

Is there any tool for this?

**Comment by namdre** [comment]
here is what you can do: 
- reprocess the nework 10 times in order to shift it spatially and also rename the node/edge ids with a prefix to avoid collisions.
- merge the 10 new networks into a single new network

Calls
`netconvert -s old.net.xml -n newINDEX.net.xml --offset.x VALUE --offset.y VALUE --prefix INDEX_`
`netconvert -s new0.net.xml,net1.net.xml,.... -o merged.net.xml`

**Comment by govin08** [comment]
@namdre Thanks. It will help a lot!
