### ISSUE TITLE
Time Series Scheduling of Parked EVs and People Occupied Schedule Around Buildings

### ISSUE THREAD

**Issue by xixihaha1995** [eclipse-sumo/sumo#14374]
I'm a newcomer to SUMO and am exploring its capabilities for simulating the following scenarios:
1. Time series of number parked Electric Vehicles (EVs) at home or in a parking lot.
2. Time series of the number of people using various modes of transportation (cars, buses, bikes, or walking) arriving or departing from specific buildings (home, office, or hospital).

If SUMO does not support these simulations, do you recommend any other tools that might be suitable for these scenarios?

**Comment by m-kro** [comment]
You can get such results from the simulation but eventually have to do some post-processing to filter the wanted data. I'd consider the following XML output for your tasks:

1. [StopOutput](https://sumo.dlr.de/docs/Simulation/Output/StopOutput.html) to gather the parked vehicles. Every stop of each vehicle is recorded (time and place). You'll have to filter out non-EV vehicles (e.g. by the ID) and which parking you consider as home / parking lot. Then 
2. This a little more difficult. The [VehRoutes](https://sumo.dlr.de/docs/Simulation/Output/VehRoutes.html) output will give you the single stages a person traveled (walk, ride). The problem is you need to filter for a set of departure/arrival locations given in the `from` or `edges` attributes afterwards.

**Comment by namdre** [comment]
a good starting point for (1) would be https://sumo.dlr.de/docs/Tools/Output.html#computestoppingplaceusagepy
