### ISSUE TITLE
Question: Meaning of some warnings

### ISSUE THREAD

**Issue by buddih09** [eclipse-sumo/sumo#14381]
Can you please explain the meaning of the following warnings and how they might affect a simulation?

Warning: Ambiguity in turnarounds computation at junction
Warning: Found angle of 146.42 degrees at edge '-100281324#1', segment 16. (I can understand what the message means, but can I ignore this without consequence?)
Warning: Shape for junction '264376282' has distance 24.87 to its given position.
Warning: Connection '982181224#1_0->745349436#0_0' is only 0.09m short.
Warning: Edge '-1034604904#1' has a grade of 718.44% (I can understand what the message means, but can I ignore this without consequence?)

Thank you.

**Comment by namdre** [comment]
- Warning: Ambiguity in turnarounds computation at junction: geometry might be ugly and right-of-way rules for turnarounds might be wrong. Recommending visual check

All the others indicate geometry problem but likely won't affect the simulation too much. Rather they are indicators that you may want to look at these spots since the raw input data *might* have been bad or misinterpreted.  If you care about grades and elevation you should recheck the grade spot.

**Comment by buddih09** [comment]
Thank you
