### ISSUE TITLE
How can I solve issues about lane changing in junction.. Thx a lot..

### ISSUE THREAD

**Issue by harrychoi618** [eclipse-sumo/sumo#14587]
I tried to run a simulation of a simple roundabout with default car following model and lane changing model, but warnings of vehicles performing emergency braking kept popping up as I ran the simulation. As I checked what's wrong with the simulation on sumo-gui, I realised some vehicles would perform lane changing at junction and vehicle entering was forced to stop. (Warning: Vehicle 'f_15.17' performs emergency braking on lane 'E0_0' with decel=9.00, wished=4.50, severity=1.00, time=242.30.) 
![螢幕擷取畫面 2024-03-24 015249](https://github.com/eclipse-sumo/sumo/assets/77225207/3b82968e-a489-4323-beff-b5cf910e9980)

Also, some vehicles would change lane right before exit and when they were blocked by the slow traffic just entered the roundabout they had to decelerate hard to exit (Warning: Vehicle 'f_21.1' performs emergency braking on lane 'E4_1' with decel=9.00, wished=4.50, severity=1.00, time=47.70).. 
![螢幕擷取畫面 2024-03-24 014408](https://github.com/eclipse-sumo/sumo/assets/77225207/838cda0e-4477-41e8-b447-8c8a1cc2e93a)

I'm still new to sumo so I tried to find if there's any solution for this issue but seems no one has even talked about it....Is there any way I can force these vehicles not changing lane at the junction? Thanks a lot..

[FYP.zip](https://github.com/eclipse-sumo/sumo/files/14733134/FYP.zip)

**SUMO-version:1.19.0**

**operating system:Win10**

**Comment by namdre** [comment]
The problem doesn't show up when simulating at the default step-length of 1. This is probably the reason why it didn't receive much attention before. 
Looking at it in detail there are two issues at play:
- a discontinuity in follower behavior when leader vehicles urgently wish to change back to the outer lane (in the step where it switches from non-urgend to urgent)
- instability in lane choice due to the way cooperative changing to the inside lane is determined (this takes into account the occupancy on the inner and outer lane in the last simulation step but doesn't do any smoothing when the occupancy changes suddenly)

**Comment by namdre** [comment]
also, there was prior observation of the issue (#13290)

**Comment by namdre** [comment]
The three issues mention above have been fixed which significantly reduces the number of warnings. Increasing step-length to 0.2 would also help (and speed up the simulation).
I'm closing this since the remaining problems are still tracked in #13290
