### ISSUE TITLE
A question about lane change in intersection，the vehicles always turn to the right lane of exit road

### ISSUE THREAD

**Issue by pjj-OSM** [eclipse-sumo/sumo#14690]
In this case, about a intersecion including edge 1 and edge 2, i have get the routes by duarouter tool.
The question is that, the vehicles in edge 1 always turn to the right lane in edge2, please look the gif below. I don't understand why the lane change like that? I think it is unrealistic.
Some parameters of lane change model is: **laneChangeModel="LC2013" lcStrategic="10" lcCooperative="1" lcSpeedGain="10" lcKeepRight="0"**,and the changeLeft and changeRight of lanes is both "all"
![intersection](https://github.com/eclipse-sumo/sumo/assets/22164090/4b8defeb-36e1-43ab-ad34-793cf5ec7b4e)
![simulation](https://github.com/eclipse-sumo/sumo/assets/22164090/af2a4b87-18c0-4f91-bacc-4e2a0ade9b27)
Please tell me what can i do to resolve this issue , thank you!

**Comment by namdre** [comment]
The reason for this is probably behind edge2. Most likely the vehicles have to do fewer lane changes if they exit edge 2 on the right lane. Can you zip and attach your whole scenario?

**Comment by pjj-OSM** [comment]
> The reason for this is probably behind edge2. Most likely the vehicles have to do fewer lane changes if they exit edge 2 on the right lane. Can you zip and attach your whole scenario?

![simulationlong](https://github.com/eclipse-sumo/sumo/assets/22164090/efd38f4d-ae0c-46b0-af6c-d37d3d553fbb)
ok,i attach a whole scenario,but likely most of vehicles  just go straight in next intersection after exit edge 2, i think it is not need to turn right in edge 2.

**Comment by ambuehll** [comment]
lcStrategic=10 is rather high. just as a link to the previous discussion.

**Comment by namdre** [comment]
> ok,i attach a whole scenario
 
I don't mean a screenshot of the whole scenario. Attach the input files (sumocfg, net.xml, rou.xml and all that zipped up)

**Comment by pjj-OSM** [comment]
> > ok,i attach a whole scenario
> 
> I don't mean a screenshot of the whole scenario. Attach the input files (sumocfg, net.xml, rou.xml and all that zipped up)

[document.zip](https://github.com/eclipse-sumo/sumo/files/14939804/document.zip)
ok, thank you!

**Comment by pjj-OSM** [comment]
> lcStrategic=10 is rather high. just as a link to the previous discussion.

thanks, i will try with a lower lcStrategic

**Comment by hongyu9876** [comment]
my experience, this will happen when:
the lane0 of edge1 is connected to [lane0, lane1, lane2] of edge2
the lane1 of edge1 is connected to [lane0, lane1, lane2] of edge2

**Comment by namdre** [comment]
Yes. The main reason for the behavior is the non-standard connection layout in your network where each lane connects to all outgoing lanes on the downstream side. Normally, connections from the same edge do not cross each other!
In SUMO vehicles use the rightmost lane that reduces the total number of lane changes to the destination. Due to your all-to-all layout the rightmost lane always has the minimum number of lane changes (in a conventional layout the left lanes would have an advantage for vehicles that have left or turning connections downstream).

Other observations:
- your simulation has many vehicles with highly circular routes (i.e. vehicle 496.1).  Besides being implausible, this causes are higher-than average number of turnarounds to be taken.  You can check your routes with https://sumo.dlr.de/docs/Tools/Routes.html#implausibleroutespy
- you have insertion backlog due to the default departSpeed of 0 (use departSpeed="avg" instead). See https://sumo.dlr.de/docs/Simulation/VehicleInsertion.html#delayed_departure
- some of the "artificial" looking lane changes result from the use of attribute `arrivalLane="random"` since vehicles have to change to reach that lane.

**Comment by pjj-OSM** [comment]
> * departSpeed

thank you for your help!

**Comment by pjj-OSM** [comment]
> Yes. The main reason for the behavior is the non-standard connection layout in your network where each lane connects to all outgoing lanes on the downstream side. Normally, connections from the same edge do not cross each other! In SUMO vehicles use the rightmost lane that reduces the total number of lane changes to the destination. Due to your all-to-all layout the rightmost lane always has the minimum number of lane changes (in a conventional layout the left lanes would have an advantage for vehicles that have left or turning connections downstream).
> 
> Other observations:
> 
> * your simulation has many vehicles with highly circular routes (i.e. vehicle 496.1).  Besides being implausible, this causes are higher-than average number of turnarounds to be taken.  You can check your routes with https://sumo.dlr.de/docs/Tools/Routes.html#implausibleroutespy
> * you have insertion backlog due to the default departSpeed of 0 (use departSpeed="avg" instead). See https://sumo.dlr.de/docs/Simulation/VehicleInsertion.html#delayed_departure
> * some of the "artificial" looking lane changes result from the use of attribute `arrivalLane="random"` since vehicles have to change to reach that lane.

thank you for your help~~
