### ISSUE TITLE
How can I prevent pedestrians from walking in the road?

### ISSUE THREAD

**Issue by govin08** [eclipse-sumo/sumo#14761]
Here are my captures from SUMO-GUI..
Some pedestrians walk on the road, even when cars are passing by.

![pedestrian_safety_0_1](https://github.com/eclipse-sumo/sumo/assets/65585738/ffc1809c-43ab-43ca-b3e5-5f43ef8a194a)
![pedestrian_safety_0_2](https://github.com/eclipse-sumo/sumo/assets/65585738/2265283b-b3a1-4252-9592-b1f289f7df5a)
![pedestrian_safety_0_3](https://github.com/eclipse-sumo/sumo/assets/65585738/7f01fc84-6324-42ad-9478-c8ea53e4fff2)
![pedestrian_safety_1_1](https://github.com/eclipse-sumo/sumo/assets/65585738/8528cc7e-458f-4549-8721-7007d3fdd43d)
![pedestrian_safety_1_2](https://github.com/eclipse-sumo/sumo/assets/65585738/cc444568-9708-42cd-bc1e-e355e6dc1304)
![pedestrian_safety_2_1](https://github.com/eclipse-sumo/sumo/assets/65585738/54592ca2-f127-4682-b171-6624b9f95851)

Pedestrians are supposed to walk within the 'sidewalk', the lane where only pedestrians are allowed, but they don't. Can I solve this problem by making [side walk with green verge](https://sumo.dlr.de/docs/images/pedestrian_network.png) ?

**Comment by govin08** [comment]
I made a green verge, but it looks awkward.
![pedestrian_safety_3_1](https://github.com/eclipse-sumo/sumo/assets/65585738/098eb8c4-8aaf-4942-9d35-42d846e750a3)

The color of green verge looks the same as the entire base color, so it doesn't look like a verge that separate car-road and pedestrian-road.

And, between the green verge and crosswalk, it looks black, meaning it is a car-road, which is weird too.

**Comment by govin08** [comment]
Modified version.

![pedestrian_safety_6](https://github.com/eclipse-sumo/sumo/assets/65585738/e2030c47-dcaf-47b5-a321-ce43c0d619e6)

**Comment by namdre** [comment]
- when a pedestrian is "on the road", can you right-click the pedestrian, open the parameter dialog and list the contents?dialog
- the black stuff beneath the walkingarea could indicate extra connections that shouldn't be part of the network model. Can you attach the network  file and the pedestrian route file (as a zip archive)?

**Comment by govin08** [comment]
1. You can check from the below captures.
![image](https://github.com/eclipse-sumo/sumo/assets/65585738/3375a462-521b-4c66-81ab-f313552ed910)
![image](https://github.com/eclipse-sumo/sumo/assets/65585738/8e44bb3d-9cfe-436e-b44f-9415288f4ef2)

2. Here are my examples
- `before_green_verge.zip` : First six captures.
- `before_green_verge.zip` : The last captures.
In each file, there's `sumocfg` file. If you double click these file, you should see the result. (If your environment is similar to mine : windows 10, sumo 1.18.0.)

[before_green_verge.zip](https://github.com/eclipse-sumo/sumo/files/15090724/before_green_verge.zip)
[after_green_verge.zip](https://github.com/eclipse-sumo/sumo/files/15090722/after_green_verge.zip)

**Comment by namdre** [comment]
The problem is purely visual: In terms of simulation interaction, the pedestrians remain on their walkingarea and do not interact with the road vehicles. The problem arises, because the default pedestrian model ("striping") treats each piece of infrastructure as having constant width. This causes visual artifacts when a wide walkingarea narrows down to meet a narrow sidewalk. Before entering the sidewalk, the pedestrians still have the full width for walking even though visually, the area has already narrowed down.  Here are some workarounds:

- reduce the difference in width  between subsequent sidewalks and also between sidewalks and crossings attached to the same walkingarea (having wider sidewalks is the easiest fix)
- switch to the jupedsim model which takes into account the real geometry of a walkingarea (still somewhat experimental: https://sumo.dlr.de/docs/Simulation/Pedestrians.html#jupedsim)

**Comment by govin08** [comment]
@namdre
So I can make the part of network where pedestrians moves more smooth, namely to eliminate the bottleneck and increase the width of the sidewalks.

So there's the jupedsim model. Thank you for recommending.
