### ISSUE TITLE
Gawron default values inconsistency between duarouter/documentation and duaIterate.py

### ISSUE THREAD

**Issue by jonasjostmann** [eclipse-sumo/sumo#14772]
The documentation of the duarouter (```main/docs/web/docs/duarouter.md```) and the script itself (```/src/duarouter/RODUAFrame.cpp```)  use these default values for the Gawron parameters:

| Option | Description |
|--------|-------------|
| **--gawron.beta** {{DT_FLOAT}} | Use FLOAT as Gawron's beta; *default:* **0.3** |
| **--gawron.a** {{DT_FLOAT}} | Use FLOAT as Gawron's a; *default:* **0.05** |

The ```main/tools/assign/duaIterate.py```, however, uses *0.5* for the alpha and  *0.9* for the beta:

```argParser.add_argument("-A", "--gA", type=float, default=.5, help="Sets Gawron's Alpha")```
```argParser.add_argument("-B", "--gBeta", type=float, default=.9, help="Sets Gawron's Beta")```

**Comment by namdre** [comment]
the values in duaIterate.py were never changed since the initial commit:
https://github.com/eclipse-sumo/sumo/commit/22ee2f8976f967bbfd1f861cb16921589914022d#diff-ef9ec561b42078d287fcc807b5d2ce5f00e5239bce86c248ef7e3a456b82f744R91-R94

the values in the C++ code were originally the same and then changed 21 years by a seemingly unrelated commit: https://github.com/eclipse-sumo/sumo/commit/54bf7967ce39a192572efce82f5d8567b14ece98#diff-eca2ce9e02e8603941ac99a924eac40d71d7aef95b582316c6d9a74329dade9b

I suspect most people use the functionality through duaIterate.py so 0.5 and 0.9 are the more *relevant* numbers.

**Comment by namdre** [comment]
Daniel Krajzewicz recalls the reason for the change: Dr. Nils Eissfeldt told him over the phone that those values were better 😄 
Daniel is happily using the duaIterate.py defaults along with everyone else, however.

**Comment by yunpangfloetteroed** [comment]
The beta value, used in Gawron's dissertation, is 0.05 (p. 47), which prevents drivers from ‘remembering’ the travel times of routes they have not used for a long time. 

The parameter a affects the convergence performance, where a = 0.5, 1 and 2 were used in Gawron's dissertation (p.48). The larger the a, the faster the convergence. Formula (4.17) helps to check if a is desirable.

**Comment by namdre** [comment]
the somewhat surprising test changes led to the discovery of #14790 and #14791
