### ISSUE TITLE
traci.vehicle.getLateralSpeed()

### ISSUE THREAD

**Issue by jianki1314** [eclipse-sumo/sumo#14826]
Why does the function（traci.vehicle.getLateralSpeed()） always get a value of 0 when I simulate, and the lane changing model uses Lc2013.Can someone answer this question，thanks.

**Comment by m-kro** [comment]
It is always 0 because by default lane changes happen instantly (within one time step) in the default lane change model. You have to use the [sublane model](https://sumo.dlr.de/docs/Simulation/SublaneModel.html) or at least define a [lane change duration](https://sumo.dlr.de/docs/Simulation/SublaneModel.html#simple_continuous_lane-change_model).
