### ISSUE TITLE
invalid error when importing lane linkage from OpenDRIVE

### ISSUE THREAD

**Issue by zlh212** [eclipse-sumo/sumo#14828]
When I use the command "netconvert --opendrive 1.xodr -o 1.net.xml --opendrive.import-all-lanes true --walkingareas true" to convert an xodr file,the following problems are displayed
![微信图片_20240507104332](https://github.com/eclipse-sumo/sumo/assets/62287281/bcbc9782-65b9-459c-86a4-d2e585b152cf)
Is there something wrong with my xodr file?

**Comment by namdre** [comment]
Yes. your file is missing obligatory attributes "elementType" and "elementId" in the "predecessor" element. What tool did you use to obtain the xodr file?

You could try setting option **--ignore-errors** but there's no guarantee something useful will come out.

**Comment by zlh212** [comment]
I used the site https://odrviewer.io/ to view the xodr file, and it worked fine. I have uploaded the xodr file in the attachment, could you please help me see if there is any problem? I converted the file to txt format because xodr format is not supported
[1.txt](https://github.com/eclipse-sumo/sumo/files/15230910/1.txt)

**Comment by namdre** [comment]
in version 1.6. the predecessor element may also occur within a lane/link and then uses different attibutes

**Comment by namdre** [comment]
The following two properties in your file are unusual:
- it contains empty `<predecessor/>` and `<successor/>` elements (which are not described in the format specification)
- it contains `<road>` elements intermixed with `<junction>` elements (instead of all the roads first and then the junctions) as observed in all previous files. The format documentation is silent on element order but all xsd schemas I found assume roads before junctions.
