### ISSUE TITLE
Appropriate Signal State for Indicating "Flashing Green" in Pedestrian Crossings

### ISSUE THREAD

**Issue by JamesPsh** [eclipse-sumo/sumo#14841]
Hello SUMO Team,

I am currently working on a traffic simulation project using SUMO,
and I'm setting up traffic lights for both vehicles and pedestrians.

In many traffic systems, the pedestrian crossing signal often transitions from a solid green light to a flashing green light to indicate that the crossing time is about to end, before switching to a red light.

I reviewed the SUMO documentation on signal state definitions
(https://sumo.dlr.de/docs/Simulation/Traffic_Lights.html#signal_state_definitions)
but couldn't find a specific mention of a "flashing green" state for pedestrian signals.

Could you advise on the best way to implement this particular state in SUMO? Is there a predefined signal state I should use, or is there a recommended method for customizing the signal to achieve this flashing green effect?

Thank you for your assistance!

**Comment by namdre** [comment]
There is currently no state that would fit *flashing green*.  What would be the expected behavior for the pedestrians?
- if you expect that they would still enter the crossing, use green
- if you expect them to stop, use red
- if you expect some of them to stop and some o them to stay, use red and also set `jmDriveAfterRedTime` in the vType

**Comment by JamesPsh** [comment]
Thank you for the clear guidance!
I will consider your suggestions in my simulation settings.

If I have further questions, I'll reach out again.
