### ISSUE TITLE
pedestrians walk directly through vehicles

### ISSUE THREAD

**Issue by zlh212** [eclipse-sumo/sumo#14846]
Why do pedestrians walk directly through vehicles when crossing the street, and is there any configuration that can be set。
![image](https://github.com/eclipse-sumo/sumo/assets/62287281/a890a27c-809f-4302-8d46-eeceb542eee2)

**Comment by m-kro** [comment]
You have a lot of turning vehicles still waiting inside the intersection. If you add more intergreen time to the signal program, they should be able to leave the intersection in time before the pedestrians.

**Comment by zlh212** [comment]
What I'm asking is, aren't pedestrians supposed to go around the traffic and cross between two cars? Why would it go right through the car? Could it have been avoided?

**Comment by namdre** [comment]
Pedestrians are not supposed to walk through cars and at least in our tests they usually don't. Are you seeing any warnings in the message window?

**Comment by zlh212** [comment]
It looks like there was no error
![image](https://github.com/eclipse-sumo/sumo/assets/62287281/91fa360c-c386-4379-8ebf-6b58f64b53e9)

**Comment by namdre** [comment]
There are plenty of warnings though! The one that explains this situation is `Person is jammed ...`.
If a person becomes jammed it will start de-congestion behavior which involves moving at reduced pace and ignoring obstacles. 
You can disable this by setting a high value for option ** --pedestrian.striping.jamtime.crossing** (default is 10).
The root cause seems to be vehicles that are stuck on the left turn and you may want to adjust the traffic light to avoid this situation.

**Comment by zlh212** [comment]
Thank you for your help
