### ISSUE TITLE
gtfs2pt.py not generating output files

### ISSUE THREAD

**Issue by jankotschy** [eclipse-sumo/sumo#14854]
When I run gtfs2pt.py, it doesn't output any files, instead this (and only runs for a few seconds():

```
jankotschy@macbook-air-7 sumo % python3 tools/import/gtfs/gtfs2pt.py -n /Users/jankotschy/Desktop/ČVUT/Bakalářka/Plzen.net.xml --gtfs /Users/jankotschy/Desktop/ČVUT/Bakalářka/gtfs.zip --date 20240506 --modes tram --vtype-output pt_vtypes.xml
function import_gtfs called at Sat, 11 May 2024 20:12:05 +0000
function import_gtfs finished after 0.291292 seconds
Reusing old resources/gtfs/numerical.net.xml
Reusing old resources/gtfs/tram.net.xml
Warning! No mapping library found, falling back to tracemapper.
```

SUMO-version: 1.19.0

operating system: macOS Sonoma
[gtfs.zip](https://github.com/eclipse-sumo/sumo/files/15283982/gtfs.zip)

**Comment by m-kro** [comment]
Some things to check:

- SUMO network and GTFS coordinates intersect/match (if no intersection is found, there is no network to map the stops/routes to)
- Does the network have the right lane permissions (for trams)?
- Was there tram service on that day (probably yes, but sometimes this can be a problem as well due to holidays, construction works etc.)
