### ISSUE TITLE
sumo-gui Road color setting

### ISSUE THREAD

**Issue by HRYEJJKUK** [eclipse-sumo/sumo#14850]
Hi.
   When I set the road color for sumo-gui, I found that I can only set it for each lane on all roads. Is it possible to not show the lane color and only show the road color?I need to have each edge render the same color instead of different lanes in the edge rendering different colors.
![image](https://github.com/eclipse-sumo/sumo/assets/121792232/02be436b-e417-4693-a8ba-19bc03b9609e)
![image](https://github.com/eclipse-sumo/sumo/assets/121792232/f6b1c6a0-b62f-4c1d-bea5-c51b22b4dd60)
**SUMO-version:sumo 1.19.0**

**operating system:win 10**

**Comment by m-kro** [comment]
Speeds (and speed limits) are computed/set mostly on lane level. That's why the colouring scheme works on lane level as well. [Edge Data](https://sumo.dlr.de/docs/Simulation/Output/Lane-_or_Edge-based_Traffic_Measures.html#value_descriptions) has mean edge speed values and can be replayed in sumo-gui using the apposite colouring scheme. If you really need this, it might be the way to go.

**Comment by HRYEJJKUK** [comment]
I need to implement using sumo-gui that the colour of the edge changes in real time with the average speed on the edge. So how do I do that? I don't find the option for edge mean speed in the following slide down menu.
![image](https://github.com/eclipse-sumo/sumo/assets/121792232/6c340585-00f9-4c7e-a491-69ddb5d67d04)

**Comment by zihaooo** [comment]
Check this out this https://github.com/eclipse-sumo/sumo/issues/14670#issuecomment-2043672370 in case you want to do it in real-time
