### ISSUE TITLE
About tlsCoordinator.py

### ISSUE THREAD

**Issue by transport45678** [eclipse-sumo/sumo#14954]
Hello,
I have two consecutively located intersection and it works with coordinated signal control. I entered duration  and order of phases in netedit and I used tlscoordinator.py tool to calculate offset. And then it loaded with additional file. When inspecting the simulation, phase sequence of one of intersection is changed. Is this expected behavior? Thank you,regards.

Add your issue description here.

*If possible, upload an example that shows your problem.*

**SUMO-version:**

**operating system:**

**Comment by namdre** [comment]
tlsCoordinator is unable to change the phase sequence since the additional file only contains an offset. Could it be that your network contains two programs for that intersection? 
By default the definition of the second program in the .net.xml is used but tlsCoordinator could write the programID of the first program and thereby switch the used program (potentially with a different sequence)

**Comment by transport45678** [comment]
I have one program for each intersection and its program ID "0".
In netedit ,first phase is like below:
![image](https://github.com/eclipse-sumo/sumo/assets/153621221/defe0fd6-6065-4c17-901d-3208df3e04ac)
When loading simulation,first phase is like below:
![image](https://github.com/eclipse-sumo/sumo/assets/153621221/25bc0a5a-e9f0-486f-b84b-f0a25ca9a752)
Also my tls.add.xml is like below:
![image](https://github.com/eclipse-sumo/sumo/assets/153621221/5213e9d9-439c-4c69-8174-709e9522cf09)

**Comment by namdre** [comment]
this is the whole point of having an offset: the program starts in another phase.

**Comment by transport45678** [comment]
Sorry for confusing
