### ISSUE TITLE
How to fix Departure time warning in sumo

### ISSUE THREAD

**Issue by shakeri1992** [eclipse-sumo/sumo#15054]
Hello, I have created my custom map with Gatcomsumo and set the number of vehicles to 100, but when I run the simulation, less number of vehicles enter the simulation and I get this message in sumo-gui :
"WARNING: Route file should be sorted by departure time"
But I want 100 vehicles to enter the network 
Any help would be greatly appreciated

**Comment by m-kro** [comment]
As a workaround you can load the route file as part of the **--additional-files**. Otherwise the  **Gatcomsumo** (a third-party product) [documentation](https://master.dl.sourceforge.net/project/gatcomsumo/v2.01/GatcomSUMO-2.01-manual-sp.pdf?viasf=1) shows  an option to generate a sorted route file. Please keep in mind to ask questions about **Gatcomsumo** on its [official contact page](https://sourceforge.net/projects/gatcomsumo/).
