### ISSUE TITLE
How to turn the dashed line between the north-south straight lane and the north-south left turn lane into a solid line

### ISSUE THREAD

**Issue by SSAreddt** [eclipse-sumo/sumo#15239]
How to turn the dashed line between the north-south straight lane and the north-south left turn lane into a solid line

**Comment by SSAreddt** [comment]
![20240718163330](https://github.com/user-attachments/assets/62d91a8e-fcaf-4252-a854-aa5f983ef1f0)Hello, my changeLeft attribute is grayed out. How should I set it

**Comment by m-kro** [comment]
@SSAreddt Please note that currently you cannot forbid lane change for all vehicle types at once because the data model of SUMO does not support that yet. You always need at least one vehicle class which is allowed to change lanes. Though you can forbid **changeLeft** and **changeRight** it for all except the vehicle class **"authority"** which will probably give you the desired result.
