### ISSUE TITLE
Can't set linkIndex attribute of connection by connection.xml

### ISSUE THREAD

**Issue by pjj-OSM** [eclipse-sumo/sumo#15242]
In this question, I found i can't set linkIndex attribute of connection by connection.xml,  although i have define linkindex value in connection.xml file after using netconvert tool, because i found the linkindex in netfile.xml is not the value i want. The result is that the traffic control(tls state) is not match the connection.
Is there the netconvert tool will compute the linkindex value again when i using netconvert tool? And the linkindex reguation is what?  
fig.1 A example of connection. In netfile, the linkindex is 43, but in my connection.xml file, the define value is 0
<img width="953" alt="fig1" src="https://github.com/user-attachments/assets/cf3c15b8-dd56-44f8-9542-4cafb60186ee">
<img width="1263" alt="fig2" src="https://github.com/user-attachments/assets/e17703b6-c1c6-4ef1-8c45-3659cf8c9cf5">

**Comment by m-kro** [comment]
From your screenshot it seems you want to set the TL linkIndex value in the PlainXML connection file. This won't work because traffc light-related content is read from the separate option **--tllogic-files** (see [netconvert input options](https://sumo.dlr.de/docs/netconvert.html#input)). You'll have to provide a separate file following [this specification](https://sumo.dlr.de/docs/Networks/PlainXML.html#traffic_light_program_definition).

**Comment by pjj-OSM** [comment]
> From your screenshot it seems you want to set the TL linkIndex value in the PlainXML connection file. This won't work because traffc light-related content is read from the separate option **--tllogic-files** (see [netconvert input options](https://sumo.dlr.de/docs/netconvert.html#input)). You'll have to provide a separate file following [this specification](https://sumo.dlr.de/docs/Networks/PlainXML.html#traffic_light_program_definition).

thank you for your patience~
