### ISSUE TITLE
Strange behavior when using randomTrips.py

### ISSUE THREAD

**Issue by paigeman** [eclipse-sumo/sumo#15306]
Hi, I am new to sumo. Recently I want to use randomTrips.py to generate `.rou.xml` that meet the following parameters.

| Parameter | Value |
| :-----------: | :------: |
|Simulation Time / s|2000|
|Number of Vehicle Nodes|300~500|
|Vehicle Movement Speed / (m/s)|15|

According to the following references,

* [How do I maintain a constant number of vehicles in the net?](https://sumo.dlr.de/docs/FAQ.html#how_do_i_maintain_a_constant_number_of_vehicles_in_the_net)
* [how can I set the vehicle to drive at a constant speed in sumo file?](https://stackoverflow.com/questions/64533948/how-can-i-set-the-vehicle-to-drive-at-a-constant-speed-in-sumo-file)
* [Automatically generating a vehicle type](https://sumo.dlr.de/docs/Tools/Trip.html#automatically_generating_a_vehicle_type)

I ran the following command.

```
python randomTrips.py -n /path/to/your/net.xml -e 2000 -p 5 --vehicle-class passenger --trip-attributes="sigma=\"0\" departSpeed=\"15\"" --intermediate 1000 -r /output/path/of/your/rou.xml
```

Then, I got a `trips.trips.xml` and my `.rou.xml` . However, the `.rou.xml` only has an empty tag 

```
<?xml version="1.0" encoding="UTF-8"?>
<routes xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="http://sumo.dlr.de/xsd/routes_file.xsd"/>
```

I am curious why would this happened.

You can get the `.net.xml` from [here](https://github.com/paigeman/Study-on-Trust-Management-Mechanism-of-Internet-of-Vehicles-Based-on-Blockchain/tree/11-deal-with-osm-map-file/net/area1).

By the way, I don't understand the meaning of this sentence in the document.

> The resulting trips are stored in an XML file (option -o, default trips.trips.xml) **suitable for [duarouter](https://sumo.dlr.de/docs/duarouter.html) which is called automatically if the option (with a filename for the resulting route file) is given**.

I think it does not tell us which option is given in the bold text.

**SUMO-version:**

Eclipse SUMO sumo Version 1.20.0

**operating system:**

Windows 11

**Comment by namdre** [comment]
- invalid (disconnected) trips are silently discarded (https://sumo.dlr.de/docs/Tools/Trip.html#validated_routes_and_trips)
- your network contains edges that have no successor (any trip starting there will be invalid) or no predecessor (any trip ending there will be invalid)
- due to option --intermediate 1000 a trip has many random intermediate steps. Any one of these steps may lead to a disconnect which makes it likely that not even one trip is valid.

For your network I recommend using the **--max-num-vehicles** + **--max-depart-delay** strategy instead of trying to create very long routes.
