### ISSUE TITLE
ModuleNotFoundError: No module named 'libsumo'

### ISSUE THREAD

**Issue by cherryh2021** [eclipse-sumo/sumo#15303]
I wanna use the libsumo and I have followed the instructions to download it. https://sumo.dlr.de/docs/Libsumo.html says that 'the binary windows release already contains the readily compiled libsumo for C++ and Java. For Python you can install it via pip install libsumo', so I downloaded the latest version SUMO1.20 from the download website. I have checked that the  "/your/path/to/sumo/tools" has been added to the PYTHONPATH environment variable.

Then I activate the virtual environment of python 3.9 and use the command 'pip install libsumo'. It comes out with error: 'ERROR: Could not install packages due to an OSError: [WinError 5] Access is denied: 'E:\\Anaconda\\envs\\cosim\\vcruntime140.dll'
Consider using the --user option or check the permissions'. So I uninstall it and turned to the command 'pip install --user libsumo'.

Now I run my python code, it still comes out with error 'ModuleNotFoundError: No module named 'libsumo''

Can anyone help me fix this error? Thank you.

**Comment by sean-reed** [comment]
You got that error because you didn't have permission to install Python packages in the system directory, you could try running the Command Prompt as an administrator before running the pip install command. With the --user option, the module gets installed to your user directory instead (so does not need root access) but it looks like that directory is not on your Python path so it can't find the module. You can see what this directory is by running the command `python -m site --user-site` and then add this path to your PYTHONPATH environment variable. In any case, this problem is not related to SUMO.

**Comment by palvarezlopez** [comment]
If after obtaining permission for installing python packages the problem remains, please reopen the ticket.
