### ISSUE TITLE
Congestion Modelling

### ISSUE THREAD

**Issue by prajwalvinod** [eclipse-sumo/sumo#15333]
Hey,

I have a very basic question. Suppose I have a very basic highway network with one on ramp regardless of size and length of network. I would like to model my demand in such a way that it causes congestion specifically in the downstream part of the ramp. Is it possible to model such a thing specifically in sumo or do I have to play with the demand file until I get what I want ?

Regards

Prajwal 

**SUMO-version: 1.16.0**

**operating system: Windows 11**

**Comment by palvarezlopez** [comment]
Hi! Try to use VariableSpeedSigns in the downstream part of the ramp. If you reduces the speed this should generate a congestion.

**Comment by namdre** [comment]
Getting a congestion with a variable speed limit is possible but a bit contrived.
If you put enough traffic on both the main highway and the on ramp, then a congestion will develop. However, this will most likely happen in the *upstream* part of the ramp since after the on-ramp there is no direct cause for congestion unless the total traffic density is extremely high.

If the total traffic after the on-ramp is extremely dense, you may see "jamming out of the blue". However, this does depend on a particular configuration of model parameters. See https://sumo.dlr.de/docs/Tutorials/FundamentalDiagram.html and https://sumo.dlr.de/docs/Simulation/RoadCapacity.html
