### ISSUE TITLE
[Question] Simulating Driver Distraction in SUMO

### ISSUE THREAD

**Issue by usamael2000** [eclipse-sumo/sumo#15359]
Hi,

If a driver were to be distracted for one or two seconds, perhaps due to using a cell phone or engaging in another activity while driving, is it possible to simulate this behaviour in SUMO?

Thank you.

**Comment by m-kro** [comment]
There is the [action steps](https://sumo.dlr.de/docs/Car-Following-Models.html#actionsteplength) feature: Let the driver take decisions less frequently than every simulation step (can be [defined per vehicle type](https://sumo.dlr.de/docs/Definition_of_Vehicles%2C_Vehicle_Types%2C_and_Routes.html#available_vtype_attributes) using the attribute `actionStepLength`). The value can be changed using [TraCI](https://sumo.dlr.de/pydoc/traci._vehicletype.html#VTypeDomain-setActionStepLength).

**Comment by robertalms** [comment]
Also have a look at the driver state device: [link](https://sumo.dlr.de/docs/Driver_State.html ). In general, this is not an easy task to tackle.

**Comment by namdre** [comment]
I think the core issue here is to have random extra steps in which no action is taken (because distraction is a non-homogeneous phenomenon).  This is already planned: #9681
You can already mimic this behavior via TraCI by overriding the current acceleration with the previous value for a single step.

**Comment by usamael2000** [comment]
Thank you so much. I will try to implement this using traci.
