### ISSUE TITLE
"Unknown vehicle class" error when using libsumo

### ISSUE THREAD

**Issue by JamesPsh** [eclipse-sumo/sumo#15389]
I'm encountering an "Unknown vehicle class" error when using libsumo and would like some assistance in resolving this issue.

Steps to reproduce the issue

1. Generate the network:
~~~
netconvert -c sumo.netccfg -o sumo.net.xml
~~~

2. Setup
```python
import sumolib
import traci
import libsumo

net = 'sumo.net.xml'
```

3. When using traci, there are no issues
```python
traci.start([sumolib.checkBinary('sumo-gui'), '-n', net])
traci.close()
```

4. However, when using libsumo, the following error occurs
```python
libsumo.start([sumolib.checkBinary('sumo'), '-n', net])
libsumo.close()

# TraCIException: Process Error
# Error: Unknown vehicle class 'container' encountered.
# Error: Unknown vehicle class 'cable_car' encountered.
# Error: Unknown vehicle class 'subway' encountered.
# Error: Unknown vehicle class 'aircraft' encountered.
# Error: Unknown vehicle class 'wheelchair' encountered.
# Error: Unknown vehicle class 'scooter' encountered.
# Error: Unknown vehicle class 'drone' encountered.
```

I am trying to use libsumo to speed up the simulation, but I am facing these errors.
I would appreciate any help or guidance to resolve this issue. Thank you!

**SUMO-version:** 1.20.0
**operating system:** windows 11

**Comment by JamesPsh** [comment]
[sample.zip](https://github.com/user-attachments/files/16778512/sample.zip)
Sample data is attached.

**Comment by namdre** [comment]
The reason is, that your network was built with netconvert version 1.20.0 which includes novel vehicle classes.
Your libsumo installation is older than version 1.20.0 and thus cannot handle these classes. 
The recommended solution is to upgrade libsumo but you could also make the network downward compatible with 
`%SUMO_HOME%\tools\net\patchVClasses.py old.net.xml -o patched.net.xml`
