### ISSUE TITLE
Sumo is not running with remote port

### ISSUE THREAD

**Issue by Kinjal-Bh** [eclipse-sumo/sumo#15398]
Hi,
Sumo seems unable to start the simulation when I am trying to start it with the remote port.

That means if I run "sumo -c <network_name.sumocfg >" in the command line it seems to work fine.
But if I run "sumo -c <network_name.sumocfg > --remote-port 8873" then it seems to hang up after saying "***Starting server on port 8873 ***". 

I have tried turning off firewall, or allowing certain ports, recheck SUMO_HOME and Path in environment variables, but nothing seem to work.

Any help is highly appreciated.

An example with sumo-gui is attached.

![image](https://github.com/user-attachments/assets/f27af234-9b5f-4a0d-869d-8cae64662b54)

**SUMO-version: 1.20.0**
**operating system: Windows**

Best regards,
Kinjal

**Comment by namdre** [comment]
if you set option **--remote-port**, sumo act as server and will wait for a TraCI client to connect.
Setting this option manually is only needed when having multiple clients (https://sumo.dlr.de/docs/TraCI/Interfacing_TraCI_from_Python.html#controlling_the_same_simulation_from_multiple_clients) Otherwise its easier to use `traci.start` which will handle launching the server and connecting to it.
