### ISSUE TITLE
Questions about vehicle behavior for edge weights.

### ISSUE THREAD

**Issue by jamongadejoa28** [eclipse-sumo/sumo#15467]
Add your issue description here.

On the route generated by randomTrips.py, vehicles are traveling more to edges with lower edge weights than to edges with higher edge weights. Why is this?

In the DST file, the 1312367594 edge has a higher weight than the 37401012 edge, but in the simulation, the vehicle actually moves more to the 37401012 edge.

*If possible, upload an example that shows your problem.*

**SUMO-version:**
[example_weights.zip](https://github.com/user-attachments/files/16958584/example_weights.zip)

1.20.0
**operating system:**
windows11

**Comment by namdre** [comment]
- 48 vehicles are randomly selected to arrive on edge 1312367594 versus 2 on edge 37401012
- In the actual simulation only 45 arrive on edge1312367594 because 1566 of the 7189 trips are discarded as unreachable during randomTrips processing.
- However, 986 vehicles pass 37401012 on their route to somewhere else because it is much more central than 1312367594. If you want to avoid this, set a high fringe-factor (i.e. 100)

I recommend using https://sumo.dlr.de/docs/Tools/Routes.html#countedgeusagepy with option --intermediate and then showing the values in sumo-gui as explained in the tool help.
