### ISSUE TITLE
Efficient way to predefine charging route for EVs

### ISSUE THREAD

**Issue by TransTony** [eclipse-sumo/sumo#15502]
Real-time searching for charging stations and rerouting EVs during simulation can be time-consuming, especially since we need to **iterate through EVs** at every simulation step. Is there an efficient way to **predefine a reasonable charging plan for some EVs**, allowing them to charge at different stations along their route, to optimize simulation performance in SUMO.

**Comment by m-kro** [comment]
In general the result of such a planning would be a route file with the individual planned stops for every EV. We don't have such script available. Do you have some resources how a "reasonable charging plan" should be generated?

**Comment by theDivj** [comment]
If you look at the Iternio API for the 'plan' get -  you can see the complexity for a 'realistic' charging route.
https://documenter.getpostman.com/view/7396339/SWTK3YsN#0796780b-0c95-46db-b003-a6387ca0ca6f

I was looking for a way to identify the 'nearest charging station on my route' in Sumo and didn't come up with anything better than brute force because there might not be a charge station actually on my route - just near it!

And as the adage says - all plans fail on contact with the enemy  - aka the simulation - charge levels aren't that predictable in any realistic simulation :)

(I guess the iteration pain only kicks in with a large number of vehicles - I haven't seen much impact iterating over several hundred vehicles - retrieving current charge level to determine whether a charge was needed - which is the point at which you need to search for a station.)

**Comment by TransTony** [comment]
Not yet developed. I believe this is more of a challenge related to the assignment of charging resources for EVs. Predefining a reasonable plan is difficult, not to mention retrieving an "equilibrium", especially for a large number of EVs.

**Comment by behrisch** [comment]
This could be an extension to duarouter but is probably out of scope
