### ISSUE TITLE
Add statistics about depleted battery in tripinfo output 

### ISSUE THREAD

**Issue by m-kro** [eclipse-sumo/sumo#15529]
Whether an EV made it with the current battery charge to its destination can only by inferred either from

- cmd output (warning messages)
- teleports / removals in case a stationfinder device is configured in parallel

Proposal:

- log whether a vehicle experienced a depleted battery
- add the information to tripinfo output

**Comment by theDivj** [comment]
Just a consideration - I find the warnings about depleted battery a pain - if you don't want to disable all warnings you can get swamped with these. (I run simulations with lots of EVs and often only want to manage a portion of these with libsumo/traci so the EVs that I haven't charged issue warnings every timestep.)

If this warning is to make any sense then shouldn't there be an option to 'park' the vehicle permanently when it runs out of charge? (rather than remove from simulation - as in the real world it would just end up stopped on the highway.) I appreciate this means the simulation end gets a bit trickier but ...

**Comment by m-kro** [comment]
@theDivj What you want is currently coupled to the [stationfinder device](https://sumo.dlr.de/docs/Simulation/Stationfinder.html#break_down_due_to_lack_of_energy): There you can define a time (parameter `rescueTime`) the vehicle will stop when running out of charge. Something else we could implement is warning only for the first time when it occurs...
