### ISSUE TITLE
Set the headway time at the entrance to a roundabout.

### ISSUE THREAD

**Issue by kasop1** [eclipse-sumo/sumo#15522]
I want to set the headway time at the entrance to the roundabout. 
Can you create a new parameter?

**Comment by namdre** [comment]
the parameter `jmTimeGapMinor` applies to roundabouts (https://sumo.dlr.de/docs/Definition_of_Vehicles%2C_Vehicle_Types%2C_and_Routes.html#junction_model_parameters)

**Comment by kasop1** [comment]
Excuse me. 
What I want to say is that I want to set the time interval when two or more vehicles enter the roundabout continuously.

**Comment by namdre** [comment]
You cannot set the headway time directly because it is an emergent property based on approach and car-following dynamics.
You can tune this with
- connection attibute `visibilityDistance` (see https://sumo.dlr.de/docs/Simulation/Intersections.html#speed_when_approaching_the_intersection)  - higher visibility leads to higher speeds and thus reduced headway when entering
- all the car-following model attributes that govern headway between vehicles in general (i.e. minGap, tau, ...)

(unless you use the mesocsopic model: https://sumo.dlr.de/docs/Simulation/Meso.html#configuration_by_edge_type)

**Comment by kasop1** [comment]
OK. 
But I have another quesetion.
Can I use this(jmTimegapMinor) now?

**Comment by kasop1** [comment]
Why does an emergency brake occur?

**Comment by namdre** [comment]
> OK. But I have another quesetion. Can I use this(jmTimegapMinor) in roundabout now?

yes

**Comment by namdre** [comment]
> Why does an emergency brake occur?

It might be a bug. See here for how to make a report: https://sumo.dlr.de/docs/FAQ.html#how_do_i_report_erroneous_behavior_of_a_sumo_application

**Comment by kasop1** [comment]
If you set jmTimegapMinor to, say, 100, emergency braking will occur.
