### ISSUE TITLE
Update documentation with current device.battery parameters

### ISSUE THREAD

**Issue by afreymann** [eclipse-sumo/sumo#15564]
I am making a simulation scenario with different electric vehicles (EVs) driving an a map. Every EV has different attribut values.
To set EV specific parameters I want to use the traci.vehicle.setParameter(...) and traci.vehicle.getParameter(...).

However, it is hard to find the current keys "device.battery. ..." which are the right one. There are different informations within the SUMO documentation.

- [Supported Device Parameters](https://sumo.dlr.de/docs/TraCI/Change_Vehicle_State.html#supported_device_parameters)
- [Other parameters for EVs](https://sumo.dlr.de/docs/Models/Electric.html#kia_soul_ev_2020)
- [There are more device parameters](https://sumo.dlr.de/docs/TraCI/Vehicle_Value_Retrieval.html#supported_device_parameters)

Which parameters are the right one for the EV, which take effect to the EV during driving?

Thanks!

**SUMO-version:**
1.20

**operating system:**
Ubuntu 20

**Comment by m-kro** [comment]
Some of the parameters have been renamed and the documentation lags a bit behind. We will shortly update the pages so that you can find the current parameter names everywhere. Generally the updated parameter names start with "device.battery".  [This page](https://sumo.dlr.de/docs/Models/Electric.html) still features a lot of the old parameter names (without "device.battery" prefix).

**Comment by namdre** [comment]
Currently, traci permits more battery device paramters for retrieval than for modification, which accounts for the difference in the two traci documentation pages.  Hence, I would advise to generate the required vehicle types with a script that outputs an XML file rather than trying to set the values via TraCI.
