### ISSUE TITLE
Error while using gtfs2pt.py

### ISSUE THREAD

**Issue by khzannat** [eclipse-sumo/sumo#15650]
Hello, 
I was using gtfs2pt.py to generate PT routes, stops etc. However, I am having an error. I have tried from cmd and the same error persists. I have not found any documentation related to the error I am having. I have checked my gtfs.zip contain all the required details needed. 
![image](https://github.com/user-attachments/assets/9f35eb42-caec-4448-ad18-9b7dfc41aa13)

**Comment by m-kro** [comment]
This is some problem with the current working directory and the folder access rights. The GTFS script needs a working directory where it is allowed to create files / folders. When called through the netedit GUI interface, the script is executed from the **tools** folder of the SUMO installation. However there the script cannot write because of limited rights.

Options:

- Call the script from the command line and from a working directory where it can write to
- Install SUMO in a directory with less limitations (if you really need the GUI interface of the tools)

**Comment by khzannat** [comment]
Thank you. The command line option worked. I tried with cmd before but made a mistake while calling the gtfs2pt.py tool. I did not include the path in double quotes.
