### ISSUE TITLE
Question about --eager-insert and --sloppy-insert.

### ISSUE THREAD

**Issue by kasop1** [eclipse-sumo/sumo#15708]
A
https://sumo.dlr.de/docs/Simulation/VehicleInsertion.html#delayed_departure
B
https://sumo.dlr.de/docs/sumo.html#processing

Could you please elaborate on -eager-insert and -sloppy-insert? I have read links A and B but did not understand them. 
It would be very easy to understand if you could explain it clearly with examples.

Also, why are the default values (eager-insert and -sloppy-insert) different in links A and B?

Thank you in advance.

**Comment by namdre** [comment]
The relevant sentence is **In older version of sumo 1) was the default and one could switch to 2) using the option --sloppy-insert. Since version 0.18.0, variant 2) is the default and one may switch to 1) using the option --eager-insert.**

Assume you have a congested road with a small gap and two vehicles that are due for insertion
- a long vehicle that doesn't fit but was meant to be inserted first
- a short vehicle that fits

The current behavior is to check that the long vehicle doesn't fit and not attempt to insert the short vehicle
If you set **--eager-insert** then the short vehicle will be checked and inserted into the gap.

Very old versions of SUMO had a different default behavior and therefore provided another option.

**Comment by kasop1** [comment]
Thanks. 
So does that mean if there are long and short cars, they might not be inserted by default?

**Comment by kasop1** [comment]
I completely understand .... 
I misunderstood your reply above. 
In any case, you are saying that the insertion of the long car is delayed (departdelay), correct?

**Comment by namdre** [comment]
The long car is delayed in both cases because it doesn't fit. The short car is delayed if the attempt to insert the long car failed (unless **--eager-insert** is set - but this may consume a lot of time if there are many insertion-delayed cars).
