### ISSUE TITLE
New problem of Emergency Braking at ALL WAY STOP (subsecond simulation)

### ISSUE THREAD

**Issue by kasop1** [eclipse-sumo/sumo#15728]
For some reason, the emergency brake is triggered. It's probably a bug. Please check.
Thank you in advance.
[bug1.zip](https://github.com/user-attachments/files/17783320/bug1.zip)

**Comment by kasop1** [comment]
#15434

**Comment by namdre** [comment]
It goes like this (times are action steps for nAV257 and nAV347:
- time=630.9:
  - nAV257 accelerates towards the intersection with commitment to enter it (after already having stopped)
  - nAV347 observes that nAV257 had more waiting time and yields
- time=631.4:
  - nAV257 enters the intersection (in the previous step it was still outside)
  - nAV347 ignores nAV257 and starts moving because
    - a) nAV257 has no waiting time
    - b) nAV257 was outside the junction in the previous step (and therefore isn't treated as a foe-on-the-intersection)
-  time=631.9:
  - nAV347 recognizes nAV257 as foe-on-the-intersection and performs emergency braking


The special state of having committed to enter an allway_stop but not having entered the intersection yet, must be taken into account to fix this.

**Comment by kasop1** [comment]
Thank you. 

But I don't understand from that comment. How should I handle it specifically? For example, please tell me the python code.

**Comment by namdre** [comment]
> Thank you.
> 
> But I don't understand from that comment. How should I handle it specifically? For example, please tell me the python code.

It's a big which I need to handle. You just have to wait for the fix

**Comment by kasop1** [comment]
I didn't know that... Yes, I see. I'll wait for the fix. Thank you very much.

**Comment by kasop1** [comment]
Thank you for your support.

Will the nightly update fix this bug and can I use the latest version of sumo tomorrow with the bug fixed?

**Comment by namdre** [comment]
yes. Nightly version from tomorrow should contain the fix

**Comment by kasop1** [comment]
Thank you very much.I will download and use it tomorrow.

**Comment by kasop1** [comment]
I installed the new version, but for some reason the emergency braking still occurs. Why?

**Comment by namdre** [comment]
Because our "nightly build" process failed to run. You can check the time stamps behind each download item at https://sumo.dlr.de/docs/Downloads.php#nightly_snapshots. As long as it says November 18, it's still the old version.

**Comment by kasop1** [comment]
Thank you very much.
You are right.
I'll make sure to check it out next time.

**Comment by namdre** [comment]
The nightly snapshot has been updated

**Comment by kasop1** [comment]
Thank you.
I checked it.
