### ISSUE TITLE
Closing a Street

### ISSUE THREAD

**Issue by khzannat** [eclipse-sumo/sumo#15830]
Hello, 
I am trying to close a street and used rerouter to define the possible routes to signpost the necessities of changing route. I have also used closingReroute to disallow vehicles on the selected edges and also mentioned <destProbReroute id="terminateRoute" probability="1"/> so that vehicle having a destination on the closing road can terminate. However, when I am trying to simulate it's still trying to use the old route and when could not find the route it terminated the simulation. I have attached herewith the network, route and config to understand what is causing the problem.   
[input.zip](https://github.com/user-attachments/files/17977679/input.zip)

**Comment by namdre** [comment]
To avoid the error, you have to set option **--device.rerouting.mode 8** (see  https://sumo.dlr.de/docs/Simulation/Rerouter.html#vehicle_behavior_when_closing_a_street)

Further notes:
- your vType configuration sets an *unsafe* value of `stepping` for the IDM model which is responsible for a lot of emergency-braking warnings. Either set a lower value for `stepping` or supress the warnings with option **----emergencydecel.warning-threshold 1.1**
- your scenario defines a lot more traffic than the road network can handle this leads to delayed insertions and slows down the simulation.  A possible remedy is option **--max-depart-delay**. See https://sumo.dlr.de/docs/Simulation/VehicleInsertion.html#delayed_departure

**Comment by khzannat** [comment]
Hi Thank you for your reply. I set the device.rerouting.mode=8 (see [additional.zip](https://github.com/user-attachments/files/18057828/additional.zip)), however, the error (Error: Vehicle '3148' has no valid route. No connection between edge '-1163451902#4' and edge '-1163451902#1') persists. Moreover, I used route sampler to generate the vehicle trajectory to match the traffic counter data. Is there any alternative that will minimise the number of vehicles generated to match the counter data? If I use max-depart-delay that may also affect the number of vehicles observed in each counter location.

**Comment by namdre** [comment]
You need at least sumo version 1.20.0 for "device.routing.mode" to take effect. The file you sent is working as expected (without error) with recent versions.

**Comment by khzannat** [comment]
Thank you so much. Do you have any suggestion to resolve the counter data issue so that the number of vehicles generated wouldn't exceed the capacity of the instance?

**Comment by namdre** [comment]
potentially, there was a problem with the routeSampler inputs or options.  Could it be the case that you had *daily traffic* counts but used those counts for a 1-hour scenario?

**Comment by khzannat** [comment]
For the whole instance, I have used multiple counter data. However, I can confirm the counter data was for 1 hour. I have extracted the hourly data from this [website](https://roadtraffic.dft.gov.uk/local-authorities/195) and the raw count is per hour data. For the route sampler I used optimize full option so that the the counter data was matched. I am not sure whether minimising vehicle would have been a better option.

**Comment by namdre** [comment]
can you provide the inputFiles and options for the routeSampler call?

**Comment by khzannat** [comment]
I have attached herewith the route sampler input file. 
[routeSampler.zip](https://github.com/user-attachments/files/18061924/routeSampler.zip)
And the option I selected for the demand generation. 
![image](https://github.com/user-attachments/assets/4c9dce81-3dc1-4b32-b6a6-97e9b603cdc0)
TIA

**Comment by namdre** [comment]
Thank you for your inputs. Your scenario gives a good show case of potential pitfalls when using routeSampler.
The core problem being that randomTrips doesn't always provide a good set of input routes to sample/optimize with.
For reference, the following tickets are a direct result of looking into the matter:

- #15880 
- #15876
- #15877
- #15881
- #15883
- #15886
- #15882

In short, to get a better scenario, perform the following steps.
- wait until tomorrow and then update to the latest development version of sumo: https://sumo.dlr.de/docs/Downloads.php#nightly_snapshots
- run randomTrips again with the following options 
```--edge-type-file value=typefactors.txt  --junction-taz --fringe-factor 100 --marouter --end 5:0:0 -o random.rou.xml```

where *typefactors.txt* has the following content:
```
highway.trunk 120
highway.primary 100
highway.secondary 80
highway.tertiary 60
```
- run routeSampler with the following options
```-r random.rou.xml --min-count 2```

This will give you traffic with far more sensible routes. Any remaining jams in the network are due to problems of network and traffic light quality. It probably helps if you rebuild your network with a newer version of netconvert or at least rebuild the traffic lights with netconvert option **--tls.rebuild**.  Things you need to look for: invalid lane-to-lane connections, missing lanes (in particular turning lanes) and missing traffic lights.
