### ISSUE TITLE
emergency braking with heterogeneous vehicle fleet

### ISSUE THREAD

**Issue by behrisch** [eclipse-sumo/sumo#15889]
see bugreports folder

**Comment by namdre** [comment]
possibly caused by slightly varying lane widths

**Comment by namdre** [comment]
in some sense this is unavoidable: assume a lane that is wide enough for two vehicles and after a junction it narrows so that it admits only one vehicle. Thus the two vehicles are in a zipper-like conflict while approaching the narrow lane, but the conflict only becomes apparent to the simulation as soon as the first vehicle enters the narrow lane and then triggers emergency braking.

**Comment by namdre** [comment]
failing tests are in `tests/sumo/sublane_model/width_transition`

**Comment by namdre** [comment]
dulicate of #3997
