### ISSUE TITLE
allow selecting of objects that are overlapped by another one

### ISSUE THREAD

**Issue by behrisch** [eclipse-sumo/sumo#2385]
currently, selection always works according to a hierarchy which prevents some objects from being selectable.

Possible solutions would be to allow a user defined hierarchy or to cycle through selectable objects by using another hotkey.

**Comment by namdre** [comment]
I would prefer cycling by repeated clicking on the same (or similar spot)

**Comment by namdre** [comment]
> 
> 
> I would prefer cycling by repeated clicking on the same (or similar spot)

The AbstractView would need to maintain
- a ring buffer of objects under the curser
- an index within the ring buffer to cycle to the next item 

The first click fills the ring buffer (by object priority as it is now)
Subsequent clicks check whether the objects under the curser are the same as in the ring buffer
- if they are the same, the index is advanced and the next object returned
- otherwise the ring buffer is reset to the new set of objects

The check for the object set avoids the need to hit the perfect clicking spot twice.
The ring-buffer manipulation should only be done on left/right click and not with every mouse movement to avoid gui slow-down.
