### ISSUE TITLE
Allow visualizing, modifying and creating TAZ

### ISSUE THREAD

**Issue by behrisch** [eclipse-sumo/sumo#3425]
new editing mode TAZ

TAZ Frame Functions:
- create TAZ:  create new taz in the same way as a polygon (attributes: id, shape, color) , 
  - checkbox: useEdgesInShape
- Edit TAZ (Frame active after clicking on a TAZ): 
  - show current taz id (no editor of attributes here, this is done in inspect mode)
  - Edges 
    - Button: select edges (changes current selection so that all edge of the TAZ are selected)
    - Button: used selected (changes TAZ edges to current selection) - default weight 1 
        - when switching from TAZ-Mode to select-mode and back, the currently edited TAZ must be remembered
    - used edges in shape (see edgesInDistrict.py)
 - Weights
   - color mode (depart, arrival, default) - sets current edge coloring mode, reset when leaving TAZ mode,
   - attributes departWeight, arrivalWeight 
   - clicking on an edge shows its current taz-edge values . Editing the value updates it for that edge and all edges of the current taz that are currently selected
   - Button: normalize weights byLength

new objects: 
- GNETAZ (id, color, shape, edges)
- GNETAZEdge (departWeight, arrivalWeight)

**Comment by palvarezlopez** [comment]
@namdre Can we considerate TAZ as the first GNERoute Element in Netedit?

**Comment by namdre** [comment]
A taz can be the first or the last element of a route definition. Actualy in this case it would be a trip rather than a route because a vehicle can only use it after filling in the missing edges with a router (using DUAROUTER or SUMO).

**Comment by palvarezlopez** [comment]
With GNERoute I mean the following hierarchy:

GNERouteElement
|
|-> GNERoute
|-> GNEVehicle
|-> GNEVehicleType
|-> GNETAZ
|-> GNETAZEdge
....

**Comment by namdre** [comment]
If GNERouteElement is meant to encapsulate elements of a route file than no. (Also, I would call it GNERouteFileElement in this case). 

TAZ and TazEdge are part of the static input which is always loaded from an additional file (not incremental like a route file).  A vehicle definition may reference a TAZ by its ID.
Thus, when loading and saving, TAZ are handled like additional elements.

Since their manipulation is more complex than that of other additionals, they can get their own mode. (Similar to how crossings get their own edit mode).
