### ISSUE TITLE
add extra penalty for turnarounds during routing

### ISSUE THREAD

**Issue by behrisch** [eclipse-sumo/sumo#4966]
Another strange corner case in routing. Suppose you have a _very short_ three lane road leaving an ordinary cross junction to the west with a corresponding three lane road entering from the same side. The vehicle in question wants to travel from north to south. Then it is cheaper to turn right and do a turnaround and turn right again than to go straight, since the lane change is not calculated as travel distance.

This happens in the ptlines2flows tests at junction 29018805 (which is a strange network anyway).

**Comment by namdre** [comment]
discouraging turn-arounds should be one of the next routing fixes

**Comment by palvarezlopez** [comment]
@namdre it's fixed?

**Comment by namdre** [comment]
It's improved with #2202 but a fixed penalty doesn't completely solve this problem because you could increase the  number of lanes (or their width) by an arbitrary amount. 
Shouldn't be a big issue in pratice though. 

At least in the ptlines2flows test, the turn-around route does not occur anymore.

**Comment by behrisch** [comment]
This ticket addresses a different topic than #2202, it is about the time needed for lane changes and not minor links. I agree that it is probably only a minor issue in real world scenarios but nevertheless we should fix it.

**Comment by namdre** [comment]
My point about #2202 was that it now at least penalizes the turnaround and thus works around this issue. I think that a proper fix for #4966 would be quite complicated because the router would have to keep track of the lane that was used to reach an edge. Basically, you would need to switch from EdgeInfo to LaneInfo and then compute a penalty for changing. 
I do not think this issue is worth the added complexity and therefore propose closing this ticket.

**Comment by behrisch** [comment]
I am still not convinced. The default minor penalty of 1.5s does not cover the time needed to travel across a junction. Can we make it depend on the size / number of lanes you need to cross when using the link? The problem with this ticket is that it may be the source of differences between the routing algorithms because it contributes to violations of the triangle inequality. And those aren't fun to debug so we should be glad about everything we find/fix "easily".

**Comment by behrisch** [comment]
Furthermore turnarounds are not always minor, so we need at least a separate turnaround penalty.

**Comment by namdre** [comment]
The current default minor penalty is for the necessary slow down on approach.
A larger value could also model the penalty due to waiting for prioritized traffic. I don't think that this correlates with junction size. The longer time to pass larger junctions is already included in the length of the internal lanes which are accounted for by the router. My point above was that a router which tracks lanes would be a bad trade-off between algorithm complexity and functionality (and not an easy fix).

Adding a special penalty for turnarounds sounds reasonable though.
