### ISSUE TITLE
Minor issues in sumolib.shapes.polygon

### ISSUE THREAD

**Issue by levente-s** [eclipse-sumo/sumo#5429]
_PolygonReader_ handles some optional attributes as required (according to the schema, only _id_ and _shape_ are required)
_Polygon_ and _PolygonReader_ does not support _geo_ and _lineWidth_ attributes

i.e. in the following test:
```
from sumolib.shapes.polygon import read

polys = read('poly.xml')
with open('poly_.xml', 'w') as f:
    f.write(polys[0].toXML())
```

poly.xml:
`<poly id="poly_0" geo="1" lineWidth="2.0" shape="9.196789,48.800859 9.198151,48.800857 9.198155,48.801756 9.196793,48.801759 9.196789,48.800859"/>`

the generated _poly\_.xml_ should be identical to _poly.xml_

**Comment by namdre** [comment]
Possibly, the PolygonReaderwill be removed in favour of the generic sumolib.xml.parse
Since d00577a5b9a1759cdb9428f88970d181a6ee4072 You can already get pretty usable polygons  by calling
`polygons = list(sumolib.xml.parse(file, 'poly', attr_conversions=sumolib.xml.DEFAULT_ATTR_CONVERSIONS))`

Missing things: #5431 #5432

**Comment by namdre** [comment]
@behrisch your thoughts on the polygonreader?

**Comment by behrisch** [comment]
I don't need it but I remember it has been used somewhere (visualization scripts maybe?). If it has no use case in our tools I think we can safely remove it.
