### ISSUE TITLE
Potential for extra help with expanding parallelization?

### ISSUE THREAD

**Issue by niniack** [eclipse-sumo/sumo#9278]
Hello!

A classmate and I are interested in working on parallelizing some functionality for SUMO as part of a class project for our _Multicore Programming_ course!

We wanted to reach out to see if there was any conversation we could get started regarding this. It looks like some functionality like lane-change is something that is potentially parallelizable? Do you believe there is some room for us to help out there or some other planned development?

**Comment by namdre** [comment]
Hello
The main question on our mind with regard to parallelization is the lack of observed speedup. Simulations limited to 1-lane roads and a sufficient number of used lanes should already parallelize well. Our best guess is that the used memory access patterns are to blame. if you could help us to understand the exact reasons and how to improve speedup that would be great.

A simple example would be a simulation with 10 parallel 1-lane roads each having the same number of vehicles running with option --threads 10. Expected speedup would be ~10 but observed speedup is ~1.5-2

**Comment by niniack** [comment]
> I'm attaching a simple scenario that should in theory permit good speedup. There are 16 independent stretches of single-lane road so all the model has to do is compute car-following behavior. The work is split evenly among the lanes so for thread numbers of 2,4,8,16 you should see linear speedup. By default, the simulation runs for 1000s but you can remove the --end option to get longer runs.
> 
> Run times (range of values in s) I'm seeing on my AMD machine with 16 cores for different values of option **--threads**:
> 
>     * 1: 9.1 - 9.5
> 
>     * 2: 19.4 - 19.9
> 
>     * 4: 14.0 - 15.1
> 
>     * 8: 10.3 - 10.5
> 
>     * 16: 6.6 - 6.8
> 
> 
> There is obviously speedup, but with bad overhead from having more than 1 thread.
> 
> I also found a regression (#9359) but we should get this fixed quickly (please use the latest development version instead of release 1.10.0 for testing)
> 
> [9278.zip](https://github.com/eclipse/sumo/files/7371225/9278.zip)

How many simulation steps is this example for?

**Comment by niniack** [comment]
Hi, @namdre thanks for providing the zip file with the config. And thank you for the tip about using the latest development version for building. We were able to recreate your results and it seems like there is some overhead with additional threads which reduces speedup. 

Could you please put us in the right direction for where to start tweaking the code for parallelization. From what I have seen so far, you seem to be using some ThreadPool implementation. We are looking to work with OpenMP for parallelization. Do you believe there is a mismatch there?

**Comment by namdre** [comment]
I believe there currently is no need to redesign parallelization in terms of which parts are synchronized, which parts are parallel and how they are distributed over the threads. If you could manage to swap out our threadpool for the OMP equivalent and just assign the same tasks as before that would be a valuable venue of research. I am not enough of an OMP export to spot a mismatch there.

Another thing that we've been thinking about is the effects of caching and memory access times. Potentially, the slowdown partially arises because cache usage works better in the non-parallelized version. If you have the means to investigate this, that would be worthwhile as well.

**Comment by namdre** [comment]
@niniack Are you still working on this?

**Comment by namdre** [comment]
Thanks for the update! I found the report quite informative.

I did some experiments on the above tests case where I tried to increase cache hit rate by putting consecutive lanes (where vehicles interact and request each others memory) into the same thread but this had no measurable impact on performance.

What I think is needed at this point is additional benchmarking to understand where the performance is lost exactly. (i.e. if the problem lies in the cache misses, which lines of code are responsible for those misses?)
