### ISSUE TITLE
Allow to edit sidewalks and bikelane width in GNECreateEdgeFrame 

### ISSUE THREAD

**Issue by palvarezlopez** [eclipse-sumo/sumo#9725]

**Comment by namdre** [comment]
It makes no sense to add these values unless they take effect!

1. sidewalkwidth implies that the edge will get a sidewalk. If somebody sets this value then the 'add sidewalk'-checkbox should 
be activated  (it's ok the other way around because then the default sidewalk width can be used)
  - also, the width must then be used for the created sidewalk!

2. bikelaneWidht impleis that the edge will get a bikelane of that width. Maybe we also want to add a checkbox for this to make it more consistent?
